kind: pipeline
type: docker
name: default

steps:
- name: kaniko
  image: plugins/kaniko
  settings:
    registry: registry.138.199.171.38.nip.io
    username: admin
    password:
      from_secret: REGISTRY_PASWORD
    repo: registry.138.199.171.38.nip.io/foo/bar
    tags: latest
    insecure: true
- name: update
  image: docker
  volumes:
  - name: app
    path: /opt/app
  - name: podman
    path: /run/podman/podman.sock
  environment:
    DOCKER_HOST: unix:///run/podman/podman.sock
    REGISTRY_PASWORD:
      from_secret: REGISTRY_PASWORD
  commands:
  - cd /opt/app
  - echo '{"insecure-registries":["registry.138.199.171.38.nip.io"]}' > /etc/docker/daemon.json
  - echo $REGISTRY_PASWORD | docker login registry.138.199.171.38.nip.io -u admin --password-stdin
  - docker pull registry.138.199.171.38.nip.io/foo/bar
  - docker compose restart test -d
volumes:
- name: app
  host:
    path: /opt/app
- name: podman
  host:
    path: /run/podman/podman.sock
