kind: pipeline
name: default

steps:
- name: kaniko
  image: plugins/kaniko
  settings:
    registry: registry.138.199.171.38.nip.io
    username: admin
    password:
      from_secret: REGISTRY_PASWORD
    repo: foo/bar
    tags: latest
    insecure: true
