kind: pipeline
type: docker
name: default

steps:
- name: kaniko
  image: plugins/kaniko
  settings:
    registry: registry.138.199.171.38.nip.io
    username: admin
    password:
      from_secret: REGISTRY_PASWORD
    repo: registry.138.199.171.38.nip.io/foo/bar
    tags: latest
    insecure: true
- name: update
  image: docker
  volumes:
  - name: app
    path: /opt/app
  commands:
  - cd /opt/app
  - ls -la
  - pwd
  - docker compose pull
  - docker compose up -d
