kind: pipeline
name: default

steps:
- name: kaniko
  image: plugins/kaniko
  settings:
    registry: registry:5000
    username: admin
    password:
      from_secret: REGISTRY_PASWORD
    repo: registry:5000/foo/bar
    tags: latest
    insecure: true
    insecure-registry: true
    skip-default-registry-fallback: true
